### PR TITLE
Restrict latest version of aeson

### PR DESCRIPTION
**Pull request by istathar**
The latest version of **aeson**, 2.2, has moved Data.Aeson.Parser's `json'` function to a new package **attoparsec-aeson**. That's fine, so far as it goes, but until that package is available in the stable Stackage resolvers we'll restrict the upper bound of **aeson** to `< 2.2`.

Will release this to Hackage as a point release to ensure ongoing support.

### CODE REVIEW

**Comment by maksbotan** [comment]
@istathar please note that `attoparsec-aeson` has lower bound on `aeson >= 2.2`, so once that's on hackage, you still won't be able to support both `aeson <2.2` and `aeson >=2.2` by using `attoparsec-aeson`.

**Comment by ysangkok** [comment]
@maksbotan an empty compat release with version 2.1 was added for attoparsec-aeson. This release works with older aeson. So I think your assertion is no longer true. You can support both. The import of the Parser module will use a different package depending on the aeson version

**Comment by istathar** [comment]
@ysangkok does that mean we can drop the `< 2.2` upper bound?

**Comment by maksbotan** [comment]
AFAIU, yes. As long as there's `aeson-attoparsec` in deps, cabal will do everything right.

I suppose you should set `<2.3` on both packages though, to keep safe from future updates.

**Pull request merged**
