### PR TITLE
Fix for GHC 9.2

### PR DESCRIPTION
**Pull request by brandon-leapyear**

### CODE REVIEW

**Comment by istathar** [comment]
Hey. Thanks for this!

I used CPP to get around the **aeson** change in another repo. We should consider employ that here (at least until Stackage has a resolver with `aeson >= 2` in it). I'll have a look shortly.

**Comment by brandonchinn178** [comment]
Oh yes, I could do that. I had thought since it was a test suite, itd be fine, but I'll make that change now

**Comment by istathar** [comment]
This is long overdue. I'll get this merged tonight.

**Comment by istathar** [comment]
Ok, I've had a go at with this, and, with the unmerged patch to **snap-core** it builds. When I tried it on an older compiler it does _not_ build, problems with **base-compat-batteries**. With `lts-18.23` the `#ifdef`s appear to work.

I will do is move your _stack.yaml_ changes out of the way (so we can keep testing with the current stable resolver working).

But before I can merge I need to work out where we are with **aeson** >= 2. It's important we get that working ASAP (though it's slightly less of a problem client side, it's still a problem).

**Comment by istathar** [comment]
Ok, got it. Will merge with my additions.

**Comment by istathar** [comment]
Thank you for your contribution @brandon-leapyear. Let me know if this regresses for you as you continue to work on GHC 9.2.1 support.

**Pull request merged**
